## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [4]:
# 1) Seu código aqui
print(f'Matemática: {(df_mat["Qt_acertos"].sum() / (24 * 100)):.2%}')
print(f'Português: {(df_por["Qt_acertos"].sum() / (18 * 100)):.2%}')
print(f'Geografia: {(df_geo["Qt_acertos"].sum() / (8 * 100)):.2%}')
print(f'Inglês: {(df_ing["Qt_acertos"].sum() / (8 * 100)):.2%}')
print(f'História: {(df_his["Qt_acertos"].sum() / (8 * 100)):.2%}')
print(f'Física: {(df_fis["Qt_acertos"].sum() / (12 * 100)):.2%}')
print(f'Química: {(df_qui["Qt_acertos"].sum() / (12 * 100)):.2%}')

pc_mat = df_mat / 24
pc_por = df_por / 18
pc_geo = df_geo /  8
pc_ing = df_ing /  8
pc_his = df_his /  8
pc_fis = df_fis /  8
pc_qui = df_qui /  8

Matemática: 49.38%
Português: 40.17%
Geografia: 42.00%
Inglês: 47.62%
História: 45.00%
Física: 44.33%
Química: 45.25%

In [5]:
# 2) Seu código aqui
df = pd.DataFrame()
df['Matemática'] = df_mat["Qt_acertos"]
df['Português'] = df_por["Qt_acertos"]
df['Geografia'] = df_geo["Qt_acertos"]
df['Inglês'] = df_ing["Qt_acertos"]
df['História'] = df_his["Qt_acertos"]
df['Física'] = df_fis["Qt_acertos"]
df['Química'] = df_qui["Qt_acertos"]
df['Total_Acertos'] = (df['Matemática'] + df['Português'] +
                      df['Geografia'] + df['Inglês'] +
                      df['História'] + df['Física'] + 
                      df['Química'])
df.head(10)

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total_Acertos
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
3,10,7,3,4,0,0,8,32
4,7,2,2,7,0,9,3,30
5,20,2,5,3,2,9,9,50
6,6,0,7,7,5,0,4,29
7,18,4,4,7,7,1,8,49
8,22,9,2,7,6,5,7,58
9,10,6,3,6,4,8,2,39

In [6]:
# 3) Seu código aqui
Qt_acertos_total = 24 + 18 + 8 + 8 + 8 + 12 + 12
df['Total_Acertos_%'] = round((df['Total_Acertos'] / 90 * 100), 2)
df.head(10)

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total_Acertos,Total_Acertos_%
0,6,7,7,3,1,8,3,35,38.89
1,19,10,0,0,0,11,8,48,53.33
2,14,16,0,5,7,4,4,50,55.56
3,10,7,3,4,0,0,8,32,35.56
4,7,2,2,7,0,9,3,30,33.33
5,20,2,5,3,2,9,9,50,55.56
6,6,0,7,7,5,0,4,29,32.22
7,18,4,4,7,7,1,8,49,54.44
8,22,9,2,7,6,5,7,58,64.44
9,10,6,3,6,4,8,2,39,43.33

In [7]:
# 4) Seu código aqui
df[df['Total_Acertos'] > 45].index.nunique()

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [11]:
# seu código aqui
# 1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado.
# Monte um novo DataFrame com os alunos desqualificados por este critério

df_eliminados = df[ (df['Matemática'] == 0) |
                         (df['Física'] == 0) |
                         (df['Química'] == 0) ]
df_eliminados.head(5)

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total_Acertos,Total_Acertos_%
3,10,7,3,4,0,0,8,32,35.56
6,6,0,7,7,5,0,4,29,32.22
10,10,8,3,2,1,7,0,31,34.44
12,20,8,3,7,1,0,3,42,46.67
14,7,11,1,7,1,4,0,31,34.44

In [12]:
# 2. Quantos são esses alunos?
df_eliminados.index.nunique()

23

In [13]:
# 3. Qual a média desses alunos em história e geografia?
print(f'Média História: {df_eliminados["História"].mean():.2}')
print(f'Média Geografia: {df_eliminados["Geografia"].mean():.2}')

Média História: 3.4
Média Geografia: 3.2

In [25]:
# 4. Monte um DataFrame com os alunos que passaram para a segunda fase.
# Repare que estes alunos não podem ter sido desqualificados
df_eliminados = df[ (df['Matemática'] != 0) &
                    (df['Física'] != 0) &
                    (df['Química'] != 0)]
df_eliminados

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total_Acertos,Total_Acertos_%
0,6,7,7,3,1,8,3,35,38.89
1,19,10,0,0,0,11,8,48,53.33
2,14,16,0,5,7,4,4,50,55.56
4,7,2,2,7,0,9,3,30,33.33
5,20,2,5,3,2,9,9,50,55.56
...,...,...,...,...,...,...,...,...,...
93,12,16,5,5,6,6,6,56,62.22
95,6,4,7,1,4,9,3,34,37.78
96,8,1,4,6,1,4,3,27,30.00
97,23,5,0,2,4,1,5,40,44.44
99,11,15,0,1,6,7,2,42,46.67

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [30]:
# arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'
# link:'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-ef18674d-d3c2-4810-bb81-0e2290124cce.c000.csv'

In [14]:
# 1) Sua solução aqui
vacAcre = pd.read_csv('https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-ef18674d-d3c2-4810-bb81-0e2290124cce.c000.csv', sep=';')
vacAcre.head(5)
# df = pd.read_csv(arquivo, sep=';')

C:\Users\perey\AppData\Local\Temp\ipykernel_23112\2255458574.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  vacAcre = pd.read_csv('https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-ef18674d-d3c2-4810-bb81-0e2290124cce.c000.csv', sep=';')

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,2129beab-a813-412e-adf1-02878b427b81-i0b0,7f22d009fc79c0e65a1a4c51542da4bbb88fb51bb631a9...,43,1978-02-15,F,4,AMARELA,120040,10,RIO BRANCO,...,2.0,Faixa Etária,217VCD228Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-01,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
1,5fb3b4b8-1035-489c-bcfb-2eef4a3dbf6e-i0b0,f04fa961fb64257ae4ab24f5ee31c22534a68c0bd4bf95...,14,2007-07-23,M,3,PARDA,120050,10,SENA MADUREIRA,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-11-10,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
2,406d10ac-6eea-4889-bd70-08f5cfc91698-i0b0,163928d20b579463c9313f1d58ce575cdd585f8afa3c1a...,33,1988-05-26,M,3,PARDA,120040,10,RIO BRANCO,...,2.0,Faixa Etária,FH4750,PFIZER,Organization/28290,2021-11-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,5fc5171d-fcca-4777-9c38-7009357bf486-i0b0,0abd1dfae4881cfa25c8cd985381ee416755b38f646d4b...,35,1986-04-19,M,3,PARDA,120040,10,RIO BRANCO,...,8.0,Trabalhadores da Educação,FJ2594,PFIZER,Organization/28290,2021-12-20,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,9c40bdcd-78df-42a2-baba-df6b6d8d2b40-i0b0,ed43984d7c86535e9493f652ae24f5c13049b6d497766e...,12,2009-12-21,F,3,PARDA,120020,10,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [15]:
vacAcre.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,2129beab-a813-412e-adf1-02878b427b81-i0b0,7f22d009fc79c0e65a1a4c51542da4bbb88fb51bb631a9...,43,1978-02-15,F,4,AMARELA,120040,10,RIO BRANCO,...,2.0,Faixa Etária,217VCD228Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-01,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
1,5fb3b4b8-1035-489c-bcfb-2eef4a3dbf6e-i0b0,f04fa961fb64257ae4ab24f5ee31c22534a68c0bd4bf95...,14,2007-07-23,M,3,PARDA,120050,10,SENA MADUREIRA,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-11-10,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
2,406d10ac-6eea-4889-bd70-08f5cfc91698-i0b0,163928d20b579463c9313f1d58ce575cdd585f8afa3c1a...,33,1988-05-26,M,3,PARDA,120040,10,RIO BRANCO,...,2.0,Faixa Etária,FH4750,PFIZER,Organization/28290,2021-11-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,5fc5171d-fcca-4777-9c38-7009357bf486-i0b0,0abd1dfae4881cfa25c8cd985381ee416755b38f646d4b...,35,1986-04-19,M,3,PARDA,120040,10,RIO BRANCO,...,8.0,Trabalhadores da Educação,FJ2594,PFIZER,Organization/28290,2021-12-20,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,9c40bdcd-78df-42a2-baba-df6b6d8d2b40-i0b0,ed43984d7c86535e9493f652ae24f5c13049b6d497766e...,12,2009-12-21,F,3,PARDA,120020,10,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [16]:
vacAcre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351187 entries, 0 to 351186
Data columns (total 32 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               351187 non-null  object
 1   paciente_id                               351187 non-null  object
 2   paciente_idade                            351187 non-null  int64
 3   paciente_dataNascimento                   351187 non-null  object
 4   paciente_enumSexoBiologico                351187 non-null  object
 5   paciente_racaCor_codigo                   351187 non-null  int64
 6   paciente_racaCor_valor                    351187 non-null  object
 7   paciente_endereco_coIbgeMunicipio         349042 non-null  object
 8   paciente_endereco_coPais                  349046 non-null  object
 9   paciente_endereco_nmMunicipio             349045 non-null  object
 10  paciente_endereco_nmPais                  349046 non-null  object
 11  paciente_endereco_uf                      349042 non-null  object
 12  paciente_endereco_cep                     316398 non-null  object
 13  paciente_nacionalidade_enumNacionalidade  351055 non-null  object
 14  estabelecimento_valor                     351187 non-null  int64
 15  estabelecimento_razaoSocial               351187 non-null  object
 16  estalecimento_noFantasia                  351187 non-null  object
 17  estabelecimento_municipio_codigo          351187 non-null  int64
 18  estabelecimento_municipio_nome            351187 non-null  object
 19  estabelecimento_uf                        351187 non-null  object
 20  vacina_grupoAtendimento_codigo            351174 non-null  float64
 21  vacina_grupoAtendimento_nome              350208 non-null  object
 22  vacina_categoria_codigo                   330791 non-null  float64
 23  vacina_categoria_nome                     330791 non-null  object
 24  vacina_lote                               351187 non-null  object
 25  vacina_fabricante_nome                    351187 non-null  object
 26  vacina_fabricante_referencia              349011 non-null  object
 27  vacina_dataAplicacao                      351187 non-null  object
 28  vacina_descricao_dose                     351187 non-null  object
 29  vacina_codigo                             351187 non-null  int64
 30  vacina_nome                               351178 non-null  object
 31  sistema_origem                            350788 non-null  object
dtypes: float64(2), int64(5), object(25)
memory usage: 85.7+ MB

In [17]:
vacAcre.shape[0]

351187

In [18]:
# 2) 
vacAcre['paciente_id'].nunique()

293235

In [19]:
# 3) 
vacAcre.loc[vacAcre['vacina_descricao_dose'] == '1ª Dose' , 'paciente_id'].nunique()

139499

In [20]:
# 3) solução alternativa
vacAcre_1dose = vacAcre[vacAcre['vacina_descricao_dose'] == '1ª Dose'].copy()
vacAcre_1dose['paciente_id'].nunique()

139499

In [21]:
# 4) 
vacAcre.loc[vacAcre['paciente_idade'] < 18, 'paciente_id'].nunique()

55452

In [55]:
# 5)
vacAcre['estalecimento_noFantasia'].nunique()

147

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
4. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
5. usando o método *.loc*, selecione somente essas variáveis  
6. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [22]:
# 1)  crie uma cópia do *DataFrame* original, contendo somente os registros de
# vacinas realizadas a menores de 18 anos. 

vacAcre_copy = vacAcre[vacAcre['paciente_idade'] < 18].copy()
vacAcre_copy.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
1,5fb3b4b8-1035-489c-bcfb-2eef4a3dbf6e-i0b0,f04fa961fb64257ae4ab24f5ee31c22534a68c0bd4bf95...,14,2007-07-23,M,3,PARDA,120050,10,SENA MADUREIRA,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-11-10,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,9c40bdcd-78df-42a2-baba-df6b6d8d2b40-i0b0,ed43984d7c86535e9493f652ae24f5c13049b6d497766e...,12,2009-12-21,F,3,PARDA,120020,10,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
8,481b2cda-d77e-425c-8b76-2a358a9abca6-i0b0,c886f14732ab0f1dff6f3f1dedb807de836fe831e7721b...,17,2004-01-04,F,4,AMARELA,120050,10,SENA MADUREIRA,...,114.0,Outros,FA9096,PFIZER,Organization/00394544000851,2021-08-11,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
9,5ff2d85e-abdd-4501-974e-3020766734fe-i0b0,fffcff498609bb25c947b6b4b0a9db3f6d16c979ac7095...,12,2009-10-10,F,3,PARDA,120020,10,CRUZEIRO DO SUL,...,2.0,Faixa Etária,31130BA,PFIZER,Organization/00394544000851,2021-10-19,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
23,611d98e1-579c-40e1-a44a-2b2fe3a398b2-i0b0,78203040a1fa305e55eba6b65451acccc24b198fb7266e...,12,2009-02-24,M,3,PARDA,120040,10,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-13,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [23]:
# 2) crie uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()
lista_colunas = list(vacAcre_copy.columns)
lista_colunas

['document_id',
 'paciente_id',
 'paciente_idade',
 'paciente_dataNascimento',
 'paciente_enumSexoBiologico',
 'paciente_racaCor_codigo',
 'paciente_racaCor_valor',
 'paciente_endereco_coIbgeMunicipio',
 'paciente_endereco_coPais',
 'paciente_endereco_nmMunicipio',
 'paciente_endereco_nmPais',
 'paciente_endereco_uf',
 'paciente_endereco_cep',
 'paciente_nacionalidade_enumNacionalidade',
 'estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf',
 'vacina_grupoAtendimento_codigo',
 'vacina_grupoAtendimento_nome',
 'vacina_categoria_codigo',
 'vacina_categoria_nome',
 'vacina_lote',
 'vacina_fabricante_nome',
 'vacina_fabricante_referencia',
 'vacina_dataAplicacao',
 'vacina_descricao_dose',
 'vacina_codigo',
 'vacina_nome',
 'sistema_origem']

In [24]:
# 3) Nesse DataFrame faça uma contagem do campo vacina_categoria_nome.

vacAcre_copy['vacina_categoria_nome'].value_counts()

Faixa Etária                                      34832
Outros                                             3701
Povos Indígenas                                    1994
Povos e Comunidades Tradicionais                    616
Trabalhadores de Saúde                              238
População Privada de Liberdade                       50
Comorbidades                                         39
Gestantes                                            23
Pessoas com Deficiência                               4
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Trabalhadores da Educação                             1
Name: vacina_categoria_nome, dtype: int64

In [25]:
# 4) a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, 
#    faça uma lista com esses valores

lista_estabelecimento = []
for i in lista_colunas:
    if 'esta'in i and 'cimento'in i:
        lista_estabelecimento.append(i)
lista_estabelecimento

['estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [26]:
# 5) usando o método .loc, selecione somente essas variáveis

vacAcre_copy.loc[vacAcre_copy['paciente_idade'] < 18, lista_estabelecimento]

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1,2002566,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE LAURO FONTES DA SILVA,120050,SENA MADUREIRA,AC
4,7232489,PREFEITURA MUNICIPAL DE SAUDE,UNIDADE DE SAUDE DA FAMILIA FRANCISCO SOUZA DO...,120020,CRUZEIRO DO SUL,AC
8,5981891,PREFEITURA MUNICIIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE MODULO I,120050,SENA MADUREIRA,AC
9,2000369,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DA SAUDE DA FAM JOSE MATHEUS ARNALDO D...,120020,CRUZEIRO DO SUL,AC
23,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
351161,2000342,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA ABEL PINHEIRO,120020,CRUZEIRO DO SUL,AC
351165,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
351166,3006166,PREFEITURA MUNICIPAL DE ACRELANDIA,UNIDADE DE SAUDE DA FAMILIA NORTON VITORINO BOHEN,120001,ACRELANDIA,AC
351171,7232489,PREFEITURA MUNICIPAL DE SAUDE,UNIDADE DE SAUDE DA FAMILIA FRANCISCO SOUZA DO...,120020,CRUZEIRO DO SUL,AC
351180,468363,REDE DE FRIOS,REDE DE FRIOS,120033,MANCIO LIMA,AC